version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-container
    ports:
      - "8732:8732"
    volumes:
      - ./source:/app/source
    working_dir: /app/source
    environment:
      - PYTHONUNBUFFERED=1
